version: '3'

services:

  sfpdfsd-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
        - sfpdfsd-backend-core
    ports:
        - "8080:80"

  sfpdfsd-backend-core:
    build:
      context: ./backend
      dockerfile: backend-core/Dockerfile
    depends_on:
      - rabbitmq
      - postgres
    ports:
      - "9090:9090"
    restart: unless-stopped

  sfpdfsd-message-processing-unit:
    build:
      context: ./backend
      dockerfile: message-processing-unit/Dockerfile
    depends_on:
      - rabbitmq
      - sfpdfsd-backend-core # 'Backend-core' has to set up the 'RabbitMQ infrastructure'
    restart: unless-stopped

  sfpdfsd-mqtt-preprocessor:
    build:
      context: ./backend
      dockerfile: mqtt-preprocessor/Dockerfile
    depends_on:
      - rabbitmq
      - mosquitto # TODO: Consider getting rid of this 'dependency' (by adding a full-fledged MQTT configuration)
      - sfpdfsd-backend-core # 'Backend-core' has to set up the 'RabbitMQ infrastructure'
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "9001:9001"
      - "1883:1883"
    volumes:
      - ./docker/mosquitto-config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./docker/mosquitto-config/password.txt:/mosquitto/config/password.txt
      - ./docker/mosquitto-data:/mosquitto/data
      - ./docker/mosquitto-log:/mosquitto/log
    restart: unless-stopped

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com # Not a real e-mail address...
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8081:80"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # RabbitMQ itself
      - "15672:15672" # Management console
